version: '3.3'
services:
  mariadb:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=ihram
    volumes:
      - erpnext_mariadb:/var/lib/mysql
      - ./mariadb.conf:/etc/mysql/conf.d
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    networks:
      - ihram-network
  ihram:
    image: purwaren/ihram:0.5-arm64
    volumes:
      - ./ihram:/home/ihram
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    networks:
      - ihram-network
networks:
  ihram-network:
    driver: bridge
    external: true
volumes:
  erpnext_mariadb:
    external: true